Hw04 lru cache completed
xkdgo/otus_golang_homeworks pull request #5
Opened 2021-09-25 19:21 UTC by xkdgo

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2021-10-10 11:37 UTC, kulti requested changes
Дмитрий, спасибо за вариант решения ДЗ.

Здорово, что попробовали сделать вариант со звездочкой 💪 Предлагаю пока сосредоточиться на основном задании. Там есть существенная ошибка в логике MoveToFront. Потокобезапость же отложить до лучших времен :)

2021-10-10 11:37 UTC, kulti commented on hw04_lru_cache/list.go
> +	i.Value = v
Можно в одну строчку `i := &ListItem{Value:v}`.

2021-10-10 11:37 UTC, kulti commented on hw04_lru_cache/list.go
> +		i.Next = nil
Эти значения и так уже nil.

2021-10-10 11:37 UTC, kulti commented on hw04_lru_cache/list.go
> +	l.PushFront(i.Value)
Это не перемещение элемента списка (Move), а удаление и создание нового. Перемещение просто изменяет порядок элементов в списке.

2021-10-10 11:37 UTC, kulti commented on hw04_lru_cache/cache_test.go
> +		c.Set(Key(strconv.Itoa(5)), 5) // ["5":5, "4":4 , "3":3, "2":2, "1":1]
Почему не `Key("5")`, как пятью строчками ниже?

2021-10-10 11:37 UTC, kulti commented on hw04_lru_cache/cache.go
> +	wg       sync.WaitGroup
Не понял, зачем нужны WaitGroup.

2021-10-10 11:37 UTC, kulti commented on hw04_lru_cache/cache.go
> +	mu       sync.Mutex
Потокобезопасность сделана некорректно. Кажется, вы еще не очень понимаете, что такое мьютекс, и что такое многопоточный код.

Предлагаю убрать это пока из кода и подождать занятий про примитивы синхронизации.

2021-10-10 11:37 UTC, kulti commented on hw04_lru_cache/cache.go
> +		cachI, _ := firstListI.Value.(*cacheItem)
Зачем `, _`?

2021-10-10 11:37 UTC, kulti commented on hw04_lru_cache/cache.go
> +	newItem.value = value
Можно в одну строчку `newItem := &cacheItem{key: key, value: value}`.

2021-10-10 18:01 UTC, xkdgo commented on hw04_lru_cache/list.go
> +	i.Value = v
Поправленно в коммите fc66c51a24c51252035bf6ba920db0400eed5678

2021-10-10 18:01 UTC, xkdgo commented on hw04_lru_cache/list.go
> +		i.Next = nil
Убрал в коммите fc66c51a24c51252035bf6ba920db0400eed5678

2021-10-10 18:02 UTC, xkdgo commented on hw04_lru_cache/list.go
> +	l.PushFront(i.Value)
Переделал в коммите fc66c51a24c51252035bf6ba920db0400eed5678

2021-10-10 18:02 UTC, xkdgo commented on hw04_lru_cache/cache_test.go
> +		c.Set(Key(strconv.Itoa(5)), 5) // ["5":5, "4":4 , "3":3, "2":2, "1":1]
Переделал в коммите fc66c51a24c51252035bf6ba920db0400eed5678

2021-10-10 18:03 UTC, xkdgo commented on hw04_lru_cache/cache.go
> +	wg       sync.WaitGroup
Да, это было явно лишним, убрано

2021-10-10 18:04 UTC, xkdgo commented on hw04_lru_cache/cache.go
> +	mu       sync.Mutex
Предложение принято, убрал, после лекции еще раз постараюсь сделать
fc66c51a24c51252035bf6ba920db0400eed5678

2021-10-10 18:05 UTC, xkdgo commented on hw04_lru_cache/cache.go
> +		cachI, _ := firstListI.Value.(*cacheItem)
Fixed

2021-10-10 18:05 UTC, xkdgo commented on hw04_lru_cache/cache.go
> +	newItem.value = value
Fixed

2021-10-11 05:01 UTC, kulti commented on hw04_lru_cache/list.go
> +	i.Value = v
В PushBack и PushFront теперь по разному написано :)

2021-10-11 05:02 UTC, kulti approved these changes
Дмитрий, спасибо за правки!

Теперь решение корректное. ДЗ принято — 10/10.

2021-12-03 21:09 UTC, merged